### ISSUE TITLE
Windows objective_function import fails - Can't pickle function object

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#133]
When using a separate `objective_function` in options an error occurs with multiprocessing on Windows:

```
Traceback (most recent call last):
  File "run_chirwut.py", line 8, in <module>
    configuration('config_chwirut.yaml')
  File "C:\Users\chris\miniconda3\envs\py37\lib\site-packages\rsopt\pkcli\optimize.py", line 26, in configuration
    H, persis_info, _ = runner.run()
  File "C:\Users\chris\miniconda3\envs\py37\lib\site-packages\rsopt\libe_tools\optimizer.py", line 74, in run
    self.alloc_specs, self.libE_specs, H0=self.H0)
  File "C:\Users\chris\miniconda3\envs\py37\lib\site-packages\libensemble\libE.py", line 232, in libE
    return libE_funcs[comms_type](sim_specs, gen_specs, exit_criteria, persis_info, alloc_specs, libE_specs, H0)
  File "C:\Users\chris\miniconda3\envs\py37\lib\site-packages\libensemble\libE.py", line 444, in libE_local
    wcomms = start_proc_team(nworkers, sim_specs, gen_specs, libE_specs)
  File "C:\Users\chris\miniconda3\envs\py37\lib\site-packages\libensemble\libE.py", line 404, in start_proc_team
    wcomm.run()
  File "C:\Users\chris\miniconda3\envs\py37\lib\site-packages\libensemble\comms\comms.py", line 261, in run
    self.process.start()
  File "C:\Users\chris\miniconda3\envs\py37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\chris\miniconda3\envs\py37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\chris\miniconda3\envs\py37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\chris\miniconda3\envs\py37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\chris\miniconda3\envs\py37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function dummy_obj at 0x00000278DD2F2E58>: import of module 'chwirut_py' failed
```

Moving the objective function import out of the configuration and into the execution of `Simulation` will move the import to the work process level and negate this issue.

**Comment by cchall** [comment]
Another that should have closed automatically
