### ISSUE TITLE
update to support libensemble 0.10.0

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#154]
- [ ] Remove `check_inputs`

**Comment by mkeilman** [comment]
This may also be a version issue: the sampler is broken. Running the python_aposmm_example gives
```
python_aposmm_example$ rsopt sample configuration config_scan_six_hump_camel.yaml
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/rsopt", line 33, in <module>
    sys.exit(load_entry_point('rsopt', 'console_scripts', 'rsopt')())
  File "/home/vagrant/src/radiasoft/rsopt/rsopt/rsopt_console.py", line 15, in main
    return pkcli.main('rsopt')
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 158, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 179, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 290, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 273, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/rsopt/rsopt/run.py", line 53, in inner
    H, persis_info, config = action(*args, **kwargs)
  File "/home/vagrant/src/radiasoft/rsopt/rsopt/pkcli/sample.py", line 20, in configuration
    H, persis_info, _ = runner.run()
  File "/home/vagrant/src/radiasoft/rsopt/rsopt/libe_tools/optimizer.py", line 70, in run
    H, persis_info, flag = libE(self.sim_specs, self.gen_specs, self.exit_criteria, self.persis_info,
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/libensemble/libE.py", line 236, in libE
    alloc_specs = ensemble.alloc_specs.dict(by_alias=True)
AttributeError: 'NoneType' object has no attribute 'dict'
```
It looks like they moved to classes from dicts:

was:
```python
self.alloc_specs = {
            "alloc_f": None,
            "out": None,
            "user": None,
            "type": "alloc",
        }
```
now:
```python
        self.alloc_specs: AllocSpecs = AllocSpecs()
```

**Comment by mkeilman** [comment]
Regarding the previous comment, a simple fix (or workaround) seems to be, e.g. in sampler.py classes:
```python
    def _configure_allocation(self):
        pass
```
That is, do nothing rather than return None.

**Comment by cchall** [comment]
Thanks for the report @mkeilman. I think we should now be compatible up to libensemble 0.10.2
Apparently there was a swap and instead of needing `alloc_specs = None` if you weren't supplying an allocation method you now need to do `alloc_specs = {}`. Since this is how rsopt initializes `alloc_specs` then nothing further is required.
