### ISSUE TITLE
Mistakes in parameter setup lead to non-obvious errors

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#21]
Something like repeated parameter names:
```
parameters = np.array([('Q1.K1', -15., 15.,  5.),
                       ('Q1.K1', -15., 15., -5.)],
                       dtype=[('name', 'U20'), ('min', 'float'), ('max', 'float'), ('start', 'float')])
```
will not be caught until libEnsemble is running giving unintuitive errors:
```
[0] libensemble.libE (ERROR): ---- Received error message from 1 ----
[0] libensemble.libE (ERROR): Message: 'NoneType' object has no attribute 'dtype'
[0] libensemble.libE (ERROR): Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 465, in run
    response = self._handle(Work)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 435, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 365, in _handle_calc
    out = calc(calc_in, Work['persis_info'], Work['libE_info'])
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 227, in run_gen
    return gen_f(calc_in, persis_info, gen_specs, libE_info)
  File "/opt/project/rsopt/libe_tools/generator_functions/local_opt_generator.py", line 46, in persistent_local_opt
    n_s, n_r = update_local_H_after_receiving(local_H, n, n_s, user_specs, Work, calc_in, fields_to_pass)
  File "/opt/project/rsopt/libe_tools/generator_functions/local_opt_generator.py", line 139, in update_local_H_after_receiving
    assert name in calc_in.dtype.names, name + " must be returned to persistent_aposmm for localopt_method: " + user_specs['localopt_method']
AttributeError: 'NoneType' object has no attribute 'dtype'
```

**Comment by cchall** [comment]
Note: should also implement #12 at the same time when I do this
