### ISSUE TITLE
FileNotFound during model.writefiles

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#35]
Running examples/elegant_fodo_example on 91cd28a3761f334d5a8dec8b74f25316605b63fd consistently results in an error with `model.write_files` unable to write out the elegant run files in the libEnsemble worker's working directory. I'm not sure how to diagnose this error and trying to make sure `os.getcwd` did not raise an error before proceeding just resulted in a timeout. I can consistently reproduce this error on my home computer but not on Jupyter. Error from ensemble.log:

```
[0] libensemble.libE (ERROR): ---- Received error message from 2 ----
[0] libensemble.libE (ERROR): Message: [Errno 2] No such file or directory
[0] libensemble.libE (ERROR): Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 465, in run
    response = self._handle(Work)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 435, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 363, in _handle_calc
    out = self._determine_dir_then_calc(Work, calc_type, calc_in, calc)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 321, in _determine_dir_then_calc
    return calc(calc_in, Work['persis_info'], Work['libE_info'])
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 220, in run_sim
    return sim_f(calc_in, persis_info, sim_specs, libE_info)
  File "/opt/project/rsopt/simulation.py", line 84, in __call__
    job._setup.generate_input_file(kwargs, '.')  # TODO: Worker needs to be in their own directory
  File "/opt/project/rsopt/configuration/setup.py", line 232, in generate_input_file
    model.write_files(directory)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/sirepo/lib.py", line 58, in write_files
    pykern.pkio.py_path(dest_dir),
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/pykern/pkio.py", line 130, in py_path
    res = py.path.local(path, expanduser=True)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/py/_path/local.py", line 163, in __init__
    self.strpath = abspath(path)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

[0] libensemble.libE (ERROR): Manager exception raised .. aborting ensemble:
[0] libensemble.libE (ERROR): Dumping ensemble history with 10 sims evaluated:
```

**Comment by robnagler** [comment]
Does libensemble remove directories? I don't think sirepo.lib removes anything so the current directory should always be valid. Busy today but I'll check it out tomorrow.

**Comment by robnagler** [comment]
I have to ask: why are you running a container on windows?

**Comment by cchall** [comment]
Mostly I've found the Docker containers work pretty well on Windows, so it's been a good environment to write code in. 

If it seems reasonable that this bug might be connected to using Windows I think there is no need to spend time on it unless someone else reports experiencing it.

**Comment by robnagler** [comment]
That's interesting. What about Windows is different than a Mac? I personally don't bother with Docker, because I like working in a VM, which is easier to manage things...

**Comment by cchall** [comment]
Closing this since it is not a major concern at this point.
I also haven't noticed it happening in quite a while.
