### ISSUE TITLE
Local import fails at run time 

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#42]
Importing from a module which imports from another module local to the worker directory fails. For example: 
```
[0] libensemble.libE (ERROR): Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 465, in run
    response = self._handle(Work)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 435, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 363, in _handle_calc
    out = self._determine_dir_then_calc(Work, calc_type, calc_in, calc)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 321, in _determine_dir_then_calc
    return calc(calc_in, Work['persis_info'], Work['libE_info'])
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/libE_worker.py", line 220, in run_sim
    return sim_f(calc_in, persis_info, sim_specs, libE_info)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/simulation.py", line 113, in __call__
    f = job.execute(**kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/configuration/jobs.py", line 76, in execute
    return self._setup.function
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/configuration/setup.py", line 170, in function
    module = pkrunpy.run_path_as_module(self.setup['input_file'])
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkrunpy.py", line 30, in run_path_as_module
    exec(code, m.__dict__)
  File "optimization_funcs.py", line 6, in <module>
    from uml_functions import lambda_und_pr, k_z_var, Ex, Ey, Ez, Bx, By, Bz
ModuleNotFoundError: No module named 'uml_functions'
```
Though module `uml_functions` is present at the time run_path_as_module is called. Trying this after the fact in an interpreter in the same directory does work. Maybe something is different when the interpreter is started in the directory verses the worker process moving there after rsopt starts?

I think this can be fixed by including `sys.path.append('.')` inside Setup.function but I'm not sure I understand the root of this problem yet.

Note: Test if this can occur with parallel python execution. A new Python process is launched from the run directory so it may not have the same bug.

**Comment by cchall** [comment]
This should be remedied now for the serial execution case by 2da7504e955bf3dbfccca69b6afb0d2963c93bb8.
Trying to trigger this problem with parallel execution did not show any issues and some background reading suggested that this is almost certainly triggered by sys.path being different for the libE worker than when I run the interpreter.
