### ISSUE TITLE
Check for for key existence when file_mapping is given

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#44]
If indentation level is wrong or keys don't exist in the file definition the error returned is very confusing

example with missing indentation level:
```
        setup:
            file_definitions: genesis_input.py  # See above
            file_mapping:  # See above
            genesis_input: genesis_commands.txt
            mg: gen.in
```

Gives:
```
Traceback (most recent call last):
  File "/global/homes/y/ypark/.local/bin/rsopt", line 8, in <module>
    sys.exit(main())
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/rsopt/rsopt_console.py", line 15, in main
    return pkcli.main('rsopt')
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/rsopt/pkcli/optimize.py", line 20, in configuration
    H, persis_info, _ = runner.run()
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/rsopt/libe_tools/optimizer.py", line 126, in run
    self._configure_libE()
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/rsopt/libe_tools/optimizer.py", line 203, in _configure_libE
    self._configure_specs()
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/rsopt/libe_tools/optimizer.py", line 170, in _configure_specs
    self.libE_specs['sim_dir_symlink_files'] = self._config.get_sym_link_list()
  File "/global/cscratch1/sd/ypark/lib/python3.8/site-packages/rsopt/configuration/configuration.py", line 86, in get_sym_link_list
    if job.setup['input_file'] not in job.setup['file_mapping'].values():
AttributeError: 'NoneType' object has no attribute 'values'
```

**Comment by cchall** [comment]
Confusing errors from improper yaml formatting is a systemic issue.
Closing this for now since user mode isn't seeing any use currently and this would require a more general fix.
