### ISSUE TITLE
Worker allocation error on rsmpi

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#51]
I have 3 x 20 core nodes and set up a job to run with 8 workers each using 4 cores and get a nodelist error from libensemble.

```
[0] libensemble.libE (ERROR): ---- Received error message from 7 ----
[0] libensemble.libE (ERROR): Message: Node list is empty - aborting
[0] libensemble.libE (ERROR): Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/worker.py", line 314, in run
    response = self._handle(Work)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/worker.py", line 284, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/worker.py", line 206, in _handle_calc
    out = calc(calc_in, Work['persis_info'], Work['libE_info'])
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/worker.py", line 149, in run_sim
    return sim_f(calc_in, persis_info, sim_specs, libE_info)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/simulation.py", line 110, in __call__
    task = exctr.submit(**job.executor_args)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/executors/mpi_executor.py", line 279, in submit
    self.workerID)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/executors/mpi_runner.py", line 94, in get_mpi_specs
    ranks_per_node, hyperthreads)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/resources/mpi_resources.py", line 82, in get_resources
    rassert(node_list, "Node list is empty - aborting")
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/resources/mpi_resources.py", line 13, in rassert
    raise ResourcesException(*args)
libensemble.resources.resources.ResourcesException: Node list is empty - aborting
```

**Comment by cchall** [comment]
4 workers x 8 cores also fails 
6 workers x 8 cores starts without any problem...

**Comment by cchall** [comment]
Source of this was pinned down. The issue has nothing to do with cores used and is just a function of nodes available and workers. See: https://github.com/Libensemble/libensemble/issues/591

For now can just make sure workers % nodes== 0 to prevent problems

**Comment by cchall** [comment]
Uneven worker distribution will be supported with the next release of libensemble
