### ISSUE TITLE
OPAL parser returns error in debug:  _pmi_alps_init:alps_get_placement_info returned with error -1

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#56]
This seems to be an issue with trying to parse OPAL input files through Shifter. The subprocess run at:
https://github.com/radiasoft/rsopt/blob/7b4aa4bc718e04177ee685a8649b47500df53055/rsopt/configuration/setup.py#L118-L123

Looks like it does complete but an error is also returned which kills rsopt:

```
Fri Apr 23 12:57:37 2021: [unset]:_pmi_alps_init:alps_get_placement_info returned with error -1
Fri Apr 23 12:57:37 2021: [unset]:_pmi_init:_pmi_alps_init returned -1
```

This occurs in the debug queue but not the interactive queue.

It may be necessary to just start logging the error, assume it is non-fatal and try to proceed. Though I worry this approach may lead to a lot of difficulty debugging if a fatal error does occur.

**Comment by robnagler** [comment]
What file is it trying to parse?

**Comment by cchall** [comment]
@robnagler The OPAL file being parsed is attached. I can send you the full set of input files separately if needed. 
[aps_linac.txt](https://github.com/radiasoft/rsopt/files/6368361/aps_linac.txt)

**Comment by robnagler** [comment]
The err is from h5py, but it only happens after sourcing /home/vagrant/.bashrc. I'm trying to figure out what in the environment is causing this.

**Comment by robnagler** [comment]
I think you need to start shifter this way:

```
--- a/rsopt/configuration/setup.py
+++ b/rsopt/configuration/setup.py
@@ -113,7 +113,7 @@ class Setup:
         if shifter:
             import shlex
             from subprocess import Popen, PIPE
-            run_string = f"shifter --image={_SHIFTER_IMAGE} /bin/bash {_SHIFTER_BASH_FILE} python {_SHIFTER_SIREPO_SCRIPT}"
+            run_string = f"srun shifter --image={_SHIFTER_IMAGE} /bin/bash {_SHIFTER_BASH_FILE} python {_SHIFTER_SIREPO_SCRIPT}"
             run_string = ' '.join([run_string, cls.NAME, input_file])
             cmd = Popen(shlex.split(run_string), stderr=PIPE, stdout=PIPE)
             out, err = cmd.communicate()
```

This seems to fix the problem. Please try and let me know.

**Comment by cchall** [comment]
Adding srun to shifter command did prevent the error for me in testing, but I now get a new error when the output is loaded.

```
Traceback (most recent call last):
  File "/global/homes/h/hallcc/.local/cori/3.8-anaconda-2020.11/bin/rsopt", line 8, in <module>
    sys.exit(main())
  File "/global/homes/h/hallcc/.local/cori/3.8-anaconda-2020.11/lib/python3.8/site-packages/rsopt/rsopt_console.py", line 15, in main
    return pkcli.main('rsopt')
  File "/global/homes/h/hallcc/.local/cori/3.8-anaconda-2020.11/lib/python3.8/site-packages/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/usr/common/software/python/3.8-anaconda-2020.11/lib/python3.8/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/usr/common/software/python/3.8-anaconda-2020.11/lib/python3.8/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/usr/common/software/python/3.8-anaconda-2020.11/lib/python3.8/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/global/homes/h/hallcc/.local/cori/3.8-anaconda-2020.11/lib/python3.8/site-packages/rsopt/pkcli/sample.py", line 8, in configuration
    _config = parse.parse_yaml_configuration(config_yaml)
  File "/global/homes/h/hallcc/.local/cori/3.8-anaconda-2020.11/lib/python3.8/site-packages/rsopt/parse.py", line 70, in parse_yaml_configuration
    job_list = _read_codes_to_jobs(template)
  File "/global/homes/h/hallcc/.local/cori/3.8-anaconda-2020.11/lib/python3.8/site-packages/rsopt/parse.py", line 40, in _read_codes_to_jobs
    new_job.setup = code_dict.get(_SETUP_FIELD) or _DEFAULT_SETUP(code_name)
  File "/global/homes/h/hallcc/.local/cori/3.8-anaconda-2020.11/lib/python3.8/site-packages/rsopt/configuration/jobs.py", line 132, in setup
    self._setup.input_file_model = self._setup.parse_input_file(self._setup.setup.get('input_file'),
  File "/global/homes/h/hallcc/.local/cori/3.8-anaconda-2020.11/lib/python3.8/site-packages/rsopt/configuration/setup.py", line 123, in parse_input_file
    d = pickle.loads(out)
_pickle.UnpicklingError: pickle data was truncated
```

**Comment by robnagler** [comment]
I don't get errors when I add this:

```diff
diff --git a/rsopt/package_data/shifter_exec.sh b/rsopt/package_data/shifter_exec.sh
index 532b09a..adc0039 100644
--- a/rsopt/package_data/shifter_exec.sh
+++ b/rsopt/package_data/shifter_exec.sh
@@ -1,15 +1,19 @@
+#!/bin/bash
+if [[ $SLURM_PROCID != 0 ]]; then
+    exit
+fi
 ulimit -c 0
 unset PYTHONPATH
 unset PYTHONSTARTUP
```

There's probably a better way to do this, e.g. with mpi4py.

**Comment by cchall** [comment]
Thanks @robnagler. I didn't realize srun by default starts 1 rank per node if not passed any arguments. 
I'm not sure if it makes a difference but my inclination was just to  ensure that only one rank is used to run the sirepo script from the start.

```
--- a/rsopt/configuration/setup.py
+++ b/rsopt/configuration/setup.py
@@ -112,12 +112,13 @@ class Setup:
         if shifter:
             import shlex
             from subprocess import Popen, PIPE
-            run_string = f"shifter --image={_SHIFTER_IMAGE} /bin/bash {_SHIFTER_BASH_FILE} python {_SHIFTER_SIREPO_SCRIPT}"
+            run_string = f"srun --ntasks 1 --nodes 1 shifter --image={_SHIFTER_IMAGE} /bin/bash {_SHIFTER_BASH_FILE} python {_SHIFTER_SIREPO_SCRIPT}"
             run_string = ' '.join([run_string, cls.NAME, input_file])
             cmd = Popen(shlex.split(run_string), stderr=PIPE, stdout=PIPE)
             out, err = cmd.communicate()
```

This seemed to work well when I tested it.

**Comment by robnagler** [comment]
Much better solution.
