### ISSUE TITLE
local optimizer freezes

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#59]
Looks like libEnsemble 0.7.2 may have broken `libEnsembleOptimizer`.

Running the chwirut examples freezes after 4 function evaluations. Killing rsopt yields:

```
  File "/Users/chall/.pyenv/versions/3.8.1/lib/python3.8/site-packages/libensemble/worker.py", line 217, in _handle_calc
    out = calc(calc_in, Work['persis_info'], Work['libE_info'])
  File "/Users/chall/.pyenv/versions/3.8.1/lib/python3.8/site-packages/libensemble/worker.py", line 154, in run_gen
    return gen_f(calc_in, persis_info, gen_specs, libE_info)
  File "/Users/chall/.pyenv/versions/3.8.1/lib/python3.8/site-packages/rsopt/libe_tools/generator_functions/local_opt_generator.py", line 65, in persistent_local_opt
    x_new = local_opter.iterate(row[fields_to_pass])
  File "/Users/chall/.pyenv/versions/3.8.1/lib/python3.8/site-packages/libensemble/gen_funcs/aposmm_localopt_support.py", line 152, in iterate
    self.parent_can_read.wait()
  File "/Users/chall/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/synchronize.py", line 349, in wait
    self._cond.wait(timeout)
  File "/Users/chall/.pyenv/versions/3.8.1/lib/python3.8/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chall/.pyenv/versions/3.8.1/lib/python3.8/site-packages/libensemble/worker.py", line 334, in run
    response = self._handle(Work)
  File "/Users/chall/.pyenv/versions/3.8.1/lib/python3.8/site-packages/libensemble/worker.py", line 294, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
  File "/Users/chall/.pyenv/versions/3.8.1/lib/python3.8/site-packages/libensemble/worker.py", line 263, in _handle_calc
    calc_status_strings.get(calc_status, "Not set"))
UnboundLocalError: local variable 'calc_status' referenced before assignment
```

**Comment by cchall** [comment]
This was a problem with DFO-LS hanging.
Finally tracked it down to something about the version of SciPy installed in my development environment. I had scipy 1.3.1 and after upgrading to scipy-1.6.3 the problem seems to have disappeared.
