### ISSUE TITLE
programmatic import failures in Runner 

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#6]
When input file definitions are provided in a module that was installed after rsopt the import will fail.
See example from @sdwebb:

$ python3 run_libE_lhc_scan.py --nworkers 2 --comm local
Traceback (most recent call last):
  File "run_libE_lhc_scan.py", line 80, in <module>
    runner = Runner(os.path.join(SCHEMA_DIR, BASE_SCHEMA.format(1)), objective_function=None, processing=test_func)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/rsopt/codes/runner/Runner.py", line 84, in _init_
    self._set_codes_from_schema()
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/rsopt/codes/runner/Runner.py", line 94, in _set_codes_from_schema
    cd['code'] = code_templates[name](options)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/rsopt/codes/runner/Templates.py", line 148, in _init_
    super(Opal, self)._init_(options)
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/rsopt/codes/runner/Templates.py", line 23, in _init_
    self.import_input()
  File "/home/vagrant/.pyenv/versions/py3/lib/python3.7/site-packages/rsopt/codes/runner/Templates.py", line 27, in import_input
    input_file_module = importlib.import_module(input_file)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/importlib/_init_.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'fastfelo'

**Comment by cchall** [comment]
This will be resolved when `Runner` is refactored for use by `Optimizer` executors unless someone besides me starts regularly having a problem with this.

Plan is to no longer dynamically import an installed module but set a module path and use https://github.com/radiasoft/pykern/blob/master/pykern/pkrunpy.py

**Comment by cchall** [comment]
pkrunpy is being used in regular rsopt execution for both serial and parallel Python function evaluation
