### ISSUE TITLE
get_objective_function fails when objective module has local imports

### ISSUE THREAD

**Issue by cchall** [radiasoft/rsopt#68]
If the module defining an objective function given to options.objective_function has local imports it expects to find then `pkrunpy.run_path_as_module` will not find them.
Adding the config execution path will not fix the issue for `run_path_as_module` but should allow `__import__` to be used.

**Comment by robnagler** [comment]
Is this a bug in pkrunpy? It probably needs to be updated anyway.

**Comment by cchall** [comment]
@robnagler I went back and double checked my test and I think I just messed up the testing. `pkrunpy.run_path_as_module` of course needs the file name/path while `__import__` only uses the module name and I did not properly switch between the two in my test.
After including  `sys.path.append(os.getcwd())` in the function where the import happens either of these options seems to work so I'll revert back to using `pkrunpy`.

**Comment by robnagler** [comment]
> After including `sys.path.append(os.getcwd())`

I do not recommend this approach. What exactly do you mean by "local imports"?

**Comment by cchall** [comment]
When I say "local imports" I am referring to Python files that are just defined where rsopt is being run and haven't been installed anywhere. if I have two modules `objective.py` and `eleproc.py` with objective importing from eleproc then I was seeing an error when rsopt was run:
```
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/rsopt", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/rsopt_console.py", line 15, in main
    return pkcli.main('rsopt')
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/pkcli/sample.py", line 32, in start
    H, persis_info, _ = runner.run()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/libe_tools/optimizer.py", line 127, in run
    self._configure_libE()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/libe_tools/optimizer.py", line 218, in _configure_libE
    self._configure_sim()
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/libe_tools/optimizer.py", line 190, in _configure_sim
    sim_function = SimulationFunction(self._config.jobs, self._config.options.get_objective_function())
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/rsopt/configuration/options.py", line 72, in get_objective_function
    module = pkrunpy.run_path_as_module(module_path)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/pykern/pkrunpy.py", line 30, in run_path_as_module
    exec(code, m.__dict__)
  File "objective.py", line 5, in <module>
    import eleproc
```
Because `os.getcwd` was not included in `sys.path` inside of `self._config.options.get_objective_function()`.

**Comment by robnagler** [comment]
Modifying `sys.path` this way is not recommended. Could be worked around with `sys.path_hooks`, which doesn't avoid the global state problem. I guess keep doing it that way. Sorry for the confusion.

**Comment by cchall** [comment]
Would implementing https://stackoverflow.com/a/39855753 avoid modifying the global state?

**Comment by robnagler** [comment]
It still modifies global state, and it actually is buggy, because if `self.path` is already in `sys.path`, then it will be removed. It's a tricky problem to monitor global state and know how to undo changes. 

For this particularly problem it's probably fine to do what you are doing since it's not a generic library that's being imported, rather rsopt is controlling execution so it is modifying other global state for other reasons.
