### ISSUE TITLE
random (lh_scan) method fails when scanning a single parameter

### ISSUE THREAD

**Issue by mkeilman** [radiasoft/rsopt#69]
The error comes from ```libensemble```:

```
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/history.py:54: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  H = np.zeros(L + len(H0), dtype=dtype_list)  # This may be more history than is needed if H0 has un-given points
/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/gen_funcs/sampling.py:136: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  H_o = np.zeros(b, dtype=gen_specs['out'])
[0] libensemble.manager (ERROR): ---- Received error message from worker 1 ----
[0] libensemble.manager (ERROR): Message: ValueError: could not broadcast input array from shape (100,1) into shape (100,)
[0] libensemble.manager (ERROR): Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/worker.py", line 334, in run
    response = self._handle(Work)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/worker.py", line 294, in _handle
    calc_out, persis_info, calc_status = self._handle_calc(Work, calc_in)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/worker.py", line 217, in _handle_calc
    out = calc(calc_in, Work['persis_info'], Work['libE_info'])
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/worker.py", line 154, in run_gen
    return gen_f(calc_in, persis_info, gen_specs, libE_info)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/gen_funcs/sampling.py", line 140, in latin_hypercube_sample
    H_o['x'] = A*(ub-lb)+lb
ValueError: could not broadcast input array from shape (100,1) into shape (100,)

[0] libensemble.libE (ERROR): Manager exception raised .. aborting ensemble:
[0] libensemble.libE (ERROR): Dumping ensemble history with 0 sims evaluated:
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/rsopt", line 33, in <module>
    sys.exit(load_entry_point('rsopt', 'console_scripts', 'rsopt')())
  File "/home/vagrant/src/radiasoft/rsopt/rsopt/rsopt_console.py", line 15, in main
    return pkcli.main('rsopt')
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 108, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/rsopt/rsopt/pkcli/sample.py", line 17, in configuration
    H, persis_info, _ = runner.run()
  File "/home/vagrant/src/radiasoft/rsopt/rsopt/libe_tools/optimizer.py", line 133, in run
    self.alloc_specs, self.libE_specs, H0=self.H0)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/libE.py", line 139, in libE
    persis_info, alloc_specs, libE_specs, H0)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/libE.py", line 340, in libE_local
    on_cleanup=cleanup)
  File "/home/vagrant/.pyenv/versions/3.7.2/envs/py3/lib/python3.7/site-packages/libensemble/libE.py", line 174, in manager
    raise LoggedException(*e.args, 'See error details above and in ensemble.log') from None
libensemble.manager.LoggedException: ('Received error message from worker 1', 'ValueError: could not broadcast input array from shape (100,1) into shape (100,)', 'See error details above and in ensemble.log')
```

There seems to be a simple workaround  to account for the deprecated numpy method, which is to replace ```return (dtype[0], dtype[1], dimension)```  with ```return dtype[0], dtype[1], (dimension,)``` in ```optimizer.set_dtype_dimension()```

**Comment by cchall** [comment]
Thanks for pointing this out and providing the fix @mkeilman !
